GAME_TYPE_SINGLE = 0;
GAME_TYPE_DOUBLE = 1;
GAME_TYPE_TWO_BALL = 2;
GAME_TYPE_FOURS = 3;

GAME_TYPE_STR = Array.new
GAME_TYPE_STR[GAME_TYPE_SINGLE] = "Jednotlivci"
GAME_TYPE_STR[GAME_TYPE_DOUBLE] = "Dvojice"
GAME_TYPE_STR[GAME_TYPE_TWO_BALL] = "Two-ball"
GAME_TYPE_STR[GAME_TYPE_FOURS] = "4 na 4"

PLAYER_POSITION_DEFENSE = 1;
PLAYER_POSITION_ATTACK = 2;
PLAYER_POSITION_TICK_1 = 4;
PLAYER_POSITION_TICK_2 = 8;
PLAYER_POSITION_TICK_5 = 16;
PLAYER_POSITION_TICK_3 = 32;

TEAM_HOME = 0;
TEAM_AWAY = 1;